"""initial journal schema

Revision ID: d1ee0e1aa0bb
Revises: 
Create Date: 2026-08-26 14:39:42.967330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1ee0e1aa0bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpaca_account_id', sa.String(length=64), nullable=False),
    sa.Column('starting_equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpaca_account_id')
    )
    op.create_table('control_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('set_by', sa.String(length=48), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equity_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('day_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('open_risk', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_dollar_delta', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equity_account_ts', 'equity_snapshots', ['account_id', sa.literal_column('ts DESC')], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('opening_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('closing_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('halted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trading_date', name='uq_session_day')
    )
    op.create_table('cycles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('regime', sa.String(length=24), nullable=True),
    sa.Column('cold_start', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cycles_session', 'cycles', ['session_id', 'started_at'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('spot', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('iv_atm', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rv_annual', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('vrp_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('iv_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('trend', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_snapshots_cycle', 'market_snapshots', ['cycle_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('structure_type', sa.String(length=32), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('spot', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('net_credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('width', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_loss', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_profit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('dollar_delta', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('regime', sa.String(length=24), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_cycle', 'proposals', ['cycle_id'], unique=False)
    op.create_table('gate_verdicts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('proposal_id', sa.BigInteger(), nullable=False),
    sa.Column('gate_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('gate_no >= 0 AND gate_no <= 12', name='ck_gate_no_range'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'gate_no', name='uq_verdict_proposal_gate')
    )
    op.create_index('ix_gate_verdicts_gate_passed', 'gate_verdicts', ['gate_no', 'passed'], unique=False)
    op.create_table('llm_memos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('proposal_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=48), nullable=False),
    sa.Column('effort', sa.String(length=16), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('fell_back', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_memos_cycle', 'llm_memos', ['cycle_id'], unique=False)
    op.create_table('proposal_legs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('proposal_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('ratio_qty', sa.Integer(), nullable=False),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_put', sa.Boolean(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ask', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('delta', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposal_legs_proposal', 'proposal_legs', ['proposal_id'], unique=False)
    op.create_table('structures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('proposal_id', sa.BigInteger(), nullable=True),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('structure_type', sa.String(length=32), nullable=True),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('net_credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_loss', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('has_resting_target', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_structures_open_underlying', 'structures', ['underlying'], unique=False, postgresql_where="status = 'open'")
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('structure_id', sa.BigInteger(), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('intent', sa.String(length=16), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('rung', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_table('fills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('filled_avg_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('partial', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fills_order', 'fills', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fills_order', table_name='fills')
    op.drop_table('fills')
    op.drop_table('orders')
    op.drop_index('ix_structures_open_underlying', table_name='structures', postgresql_where="status = 'open'")
    op.drop_table('structures')
    op.drop_index('ix_proposal_legs_proposal', table_name='proposal_legs')
    op.drop_table('proposal_legs')
    op.drop_index('ix_llm_memos_cycle', table_name='llm_memos')
    op.drop_table('llm_memos')
    op.drop_index('ix_gate_verdicts_gate_passed', table_name='gate_verdicts')
    op.drop_table('gate_verdicts')
    op.drop_index('ix_proposals_cycle', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('ix_market_snapshots_cycle', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('ix_cycles_session', table_name='cycles')
    op.drop_table('cycles')
    op.drop_table('sessions')
    op.drop_index('ix_equity_account_ts', table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    op.drop_table('control_flags')
    op.drop_table('accounts')
    # ### end Alembic commands ###
